### PR TITLE
feat: Add changing positioning customization

### LINKED ISSUE #3: feat: Support for changing position
The current implementation of the Vue Hot Toast library doesn't provide an option to change the position of toast notifications on the screen. It's essential to have a feature that allows custom positioning of toast notifications like top-center, bottom-left, bottom-right, etc., to provide flexibility in how toast notifications are displayed in different application layouts.

TODO: Support for changing position, like `top-center`... etc 6 positions of screen

### PR DESCRIPTION
**Pull request by HarryZ10**
Adds functionality of positioning.

Closes #3

### CODE REVIEW

**Comment by HarryZ10** [comment]
@SteveYuOWO Let me know if that lockfile contribution was necessary for the gitignore. I can remove that if not!

**Comment by HarryZ10** [comment]
@SteveYuOWO

**Comment by HarryZ10** [comment]
@SteveYuOWO

**Comment by ayonkov1** [comment]
HI, looks good. Why not approve?

**Review by SteveYuOWO — APPROVED** [review]

**Comment by SteveYuOWO** [comment]
cool.

**Comment by SteveYuOWO** [comment]
@HarryZ10  Cool. thank u for cooking this pr. 🥰 🥰 🥰

**Pull request merged**
